container:
  kubernetes: &kubernetes
    gitEnvFrom:
      - secretRef:
          name: oss-github-ssh-credentials
    podSpec: &podSpec
      containers:
        - &commandContainer
          image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-command-container:v2
          command:
          - |-
            echo "Command step was not overridden."
            exit 1

steps:
  - label: "proto lint"
    agents:
      queue: "buildkite-gcp"
    plugins:
      - kubernetes:
          <<: *kubernetes
          podSpec:
            <<: *podSpec
            containers:
              - <<: *commandContainer
                command:
                - |-
                  make proto-lint

  - label: "thrift compile"
    agents:
      queue: "buildkite-gcp"
    plugins:
      - kubernetes:
          <<: *kubernetes
          podSpec:
            <<: *podSpec
            containers:
              - <<: *commandContainer
                command:
                - |-
                  # Install thrift compiler
                  apt-get update && apt-get install -y thrift-compiler
                  # Compile all thrift files to check for syntax errors
                  cd thrift
                  for file in *.thrift; do
                    echo "Compiling $file..."
                    thrift --gen go "$file"
                  done
                  echo "All Thrift files compiled successfully!"
