// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uber/cadence/api/v1/schedule.proto

package apiv1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ScheduleOverlapPolicy defines behavior when a new run is scheduled while a previous run is still active.
type ScheduleOverlapPolicy int32

const (
	ScheduleOverlapPolicy_SCHEDULE_OVERLAP_POLICY_INVALID ScheduleOverlapPolicy = 0
	// Skip the new run if the previous is still running.
	ScheduleOverlapPolicy_SCHEDULE_OVERLAP_POLICY_SKIP ScheduleOverlapPolicy = 1
	// Buffer one run and skip the rest.
	ScheduleOverlapPolicy_SCHEDULE_OVERLAP_POLICY_BUFFER_ONE ScheduleOverlapPolicy = 2
	// Buffer all runs up to a limit.
	ScheduleOverlapPolicy_SCHEDULE_OVERLAP_POLICY_BUFFER_ALL ScheduleOverlapPolicy = 3
	// Cancel the previous run and start a new one.
	ScheduleOverlapPolicy_SCHEDULE_OVERLAP_POLICY_CANCEL_OTHER ScheduleOverlapPolicy = 4
	// Terminate the previous run and start a new one.
	ScheduleOverlapPolicy_SCHEDULE_OVERLAP_POLICY_TERMINATE_OTHER ScheduleOverlapPolicy = 5
	// Allow all runs concurrently.
	ScheduleOverlapPolicy_SCHEDULE_OVERLAP_POLICY_ALLOW_ALL ScheduleOverlapPolicy = 6
)

var ScheduleOverlapPolicy_name = map[int32]string{
	0: "SCHEDULE_OVERLAP_POLICY_INVALID",
	1: "SCHEDULE_OVERLAP_POLICY_SKIP",
	2: "SCHEDULE_OVERLAP_POLICY_BUFFER_ONE",
	3: "SCHEDULE_OVERLAP_POLICY_BUFFER_ALL",
	4: "SCHEDULE_OVERLAP_POLICY_CANCEL_OTHER",
	5: "SCHEDULE_OVERLAP_POLICY_TERMINATE_OTHER",
	6: "SCHEDULE_OVERLAP_POLICY_ALLOW_ALL",
}

var ScheduleOverlapPolicy_value = map[string]int32{
	"SCHEDULE_OVERLAP_POLICY_INVALID":         0,
	"SCHEDULE_OVERLAP_POLICY_SKIP":            1,
	"SCHEDULE_OVERLAP_POLICY_BUFFER_ONE":      2,
	"SCHEDULE_OVERLAP_POLICY_BUFFER_ALL":      3,
	"SCHEDULE_OVERLAP_POLICY_CANCEL_OTHER":    4,
	"SCHEDULE_OVERLAP_POLICY_TERMINATE_OTHER": 5,
	"SCHEDULE_OVERLAP_POLICY_ALLOW_ALL":       6,
}

func (x ScheduleOverlapPolicy) String() string {
	return proto.EnumName(ScheduleOverlapPolicy_name, int32(x))
}

func (ScheduleOverlapPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7fe71309dc9555dc, []int{0}
}

// ScheduleCatchUpPolicy defines how missed runs are handled on unpause or system recovery.
type ScheduleCatchUpPolicy int32

const (
	ScheduleCatchUpPolicy_SCHEDULE_CATCH_UP_POLICY_INVALID ScheduleCatchUpPolicy = 0
	// Skip all missed runs.
	ScheduleCatchUpPolicy_SCHEDULE_CATCH_UP_POLICY_SKIP ScheduleCatchUpPolicy = 1
	// Run once for all missed runs.
	ScheduleCatchUpPolicy_SCHEDULE_CATCH_UP_POLICY_ONE ScheduleCatchUpPolicy = 2
	// Run for each missed run (up to the catch-up window).
	ScheduleCatchUpPolicy_SCHEDULE_CATCH_UP_POLICY_ALL ScheduleCatchUpPolicy = 3
)

var ScheduleCatchUpPolicy_name = map[int32]string{
	0: "SCHEDULE_CATCH_UP_POLICY_INVALID",
	1: "SCHEDULE_CATCH_UP_POLICY_SKIP",
	2: "SCHEDULE_CATCH_UP_POLICY_ONE",
	3: "SCHEDULE_CATCH_UP_POLICY_ALL",
}

var ScheduleCatchUpPolicy_value = map[string]int32{
	"SCHEDULE_CATCH_UP_POLICY_INVALID": 0,
	"SCHEDULE_CATCH_UP_POLICY_SKIP":    1,
	"SCHEDULE_CATCH_UP_POLICY_ONE":     2,
	"SCHEDULE_CATCH_UP_POLICY_ALL":     3,
}

func (x ScheduleCatchUpPolicy) String() string {
	return proto.EnumName(ScheduleCatchUpPolicy_name, int32(x))
}

func (ScheduleCatchUpPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7fe71309dc9555dc, []int{1}
}

// ScheduleSpec defines when a schedule should trigger.
type ScheduleSpec struct {
	// Standard cron expression (e.g., "0 6 * * *").
	// Timezone can be embedded using CRON_TZ prefix (e.g., "CRON_TZ=America/Los_Angeles 0 6 * * *").
	// Defaults to UTC if no timezone specified.
	CronExpression string `protobuf:"bytes,1,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	// Earliest time the schedule should trigger. If not set, starts immediately.
	StartTime *types.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Latest time the schedule should trigger. If not set, runs indefinitely.
	EndTime              *types.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ScheduleSpec) Reset()         { *m = ScheduleSpec{} }
func (m *ScheduleSpec) String() string { return proto.CompactTextString(m) }
func (*ScheduleSpec) ProtoMessage()    {}
func (*ScheduleSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe71309dc9555dc, []int{0}
}
func (m *ScheduleSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduleSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduleSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduleSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleSpec.Merge(m, src)
}
func (m *ScheduleSpec) XXX_Size() int {
	return m.Size()
}
func (m *ScheduleSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleSpec proto.InternalMessageInfo

func (m *ScheduleSpec) GetCronExpression() string {
	if m != nil {
		return m.CronExpression
	}
	return ""
}

func (m *ScheduleSpec) GetStartTime() *types.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ScheduleSpec) GetEndTime() *types.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

// ScheduleAction defines the workflow to start when the schedule triggers.
type ScheduleAction struct {
	// Name of the workflow type to start.
	WorkflowType string `protobuf:"bytes,1,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	// Task list for the target workflow.
	TaskList string `protobuf:"bytes,2,opt,name=task_list,json=taskList,proto3" json:"task_list,omitempty"`
	// Input payload for the target workflow.
	Input *Payload `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	// Prefix for generating the target workflow ID.
	// Target workflow ID: {workflow_id_prefix}-{scheduled_time_unix_nanos}
	WorkflowIdPrefix string `protobuf:"bytes,4,opt,name=workflow_id_prefix,json=workflowIdPrefix,proto3" json:"workflow_id_prefix,omitempty"`
	// Execution timeout for the target workflow.
	ExecutionStartToCloseTimeout *types.Duration `protobuf:"bytes,5,opt,name=execution_start_to_close_timeout,json=executionStartToCloseTimeout,proto3" json:"execution_start_to_close_timeout,omitempty"`
	// Decision task timeout for the target workflow.
	TaskStartToCloseTimeout *types.Duration `protobuf:"bytes,6,opt,name=task_start_to_close_timeout,json=taskStartToCloseTimeout,proto3" json:"task_start_to_close_timeout,omitempty"`
	// Retry policy for the target workflow.
	RetryPolicy *RetryPolicy `protobuf:"bytes,7,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	// Additional memo data to attach to the target workflow.
	Memo *Memo `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	// Search attributes to attach to the target workflow.
	SearchAttributes     *SearchAttributes `protobuf:"bytes,9,opt,name=search_attributes,json=searchAttributes,proto3" json:"search_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ScheduleAction) Reset()         { *m = ScheduleAction{} }
func (m *ScheduleAction) String() string { return proto.CompactTextString(m) }
func (*ScheduleAction) ProtoMessage()    {}
func (*ScheduleAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe71309dc9555dc, []int{1}
}
func (m *ScheduleAction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduleAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduleAction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduleAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleAction.Merge(m, src)
}
func (m *ScheduleAction) XXX_Size() int {
	return m.Size()
}
func (m *ScheduleAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleAction.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleAction proto.InternalMessageInfo

func (m *ScheduleAction) GetWorkflowType() string {
	if m != nil {
		return m.WorkflowType
	}
	return ""
}

func (m *ScheduleAction) GetTaskList() string {
	if m != nil {
		return m.TaskList
	}
	return ""
}

func (m *ScheduleAction) GetInput() *Payload {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *ScheduleAction) GetWorkflowIdPrefix() string {
	if m != nil {
		return m.WorkflowIdPrefix
	}
	return ""
}

func (m *ScheduleAction) GetExecutionStartToCloseTimeout() *types.Duration {
	if m != nil {
		return m.ExecutionStartToCloseTimeout
	}
	return nil
}

func (m *ScheduleAction) GetTaskStartToCloseTimeout() *types.Duration {
	if m != nil {
		return m.TaskStartToCloseTimeout
	}
	return nil
}

func (m *ScheduleAction) GetRetryPolicy() *RetryPolicy {
	if m != nil {
		return m.RetryPolicy
	}
	return nil
}

func (m *ScheduleAction) GetMemo() *Memo {
	if m != nil {
		return m.Memo
	}
	return nil
}

func (m *ScheduleAction) GetSearchAttributes() *SearchAttributes {
	if m != nil {
		return m.SearchAttributes
	}
	return nil
}

// SchedulePolicies configures schedule behavior.
type SchedulePolicies struct {
	// Defines what happens when a new run is scheduled while the previous is still running.
	OverlapPolicy ScheduleOverlapPolicy `protobuf:"varint,1,opt,name=overlap_policy,json=overlapPolicy,proto3,enum=uber.cadence.api.v1.ScheduleOverlapPolicy" json:"overlap_policy,omitempty"`
	// Defines how missed runs are handled on unpause or system recovery.
	CatchUpPolicy ScheduleCatchUpPolicy `protobuf:"varint,2,opt,name=catch_up_policy,json=catchUpPolicy,proto3,enum=uber.cadence.api.v1.ScheduleCatchUpPolicy" json:"catch_up_policy,omitempty"`
	// Maximum time to look back for missed runs. Runs older than this window are skipped.
	CatchUpWindow *types.Duration `protobuf:"bytes,3,opt,name=catch_up_window,json=catchUpWindow,proto3" json:"catch_up_window,omitempty"`
	// If true, pause the schedule when a triggered workflow fails.
	PauseOnFailure       bool     `protobuf:"varint,4,opt,name=pause_on_failure,json=pauseOnFailure,proto3" json:"pause_on_failure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchedulePolicies) Reset()         { *m = SchedulePolicies{} }
func (m *SchedulePolicies) String() string { return proto.CompactTextString(m) }
func (*SchedulePolicies) ProtoMessage()    {}
func (*SchedulePolicies) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe71309dc9555dc, []int{2}
}
func (m *SchedulePolicies) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SchedulePolicies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SchedulePolicies.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SchedulePolicies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulePolicies.Merge(m, src)
}
func (m *SchedulePolicies) XXX_Size() int {
	return m.Size()
}
func (m *SchedulePolicies) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulePolicies.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulePolicies proto.InternalMessageInfo

func (m *SchedulePolicies) GetOverlapPolicy() ScheduleOverlapPolicy {
	if m != nil {
		return m.OverlapPolicy
	}
	return ScheduleOverlapPolicy_SCHEDULE_OVERLAP_POLICY_INVALID
}

func (m *SchedulePolicies) GetCatchUpPolicy() ScheduleCatchUpPolicy {
	if m != nil {
		return m.CatchUpPolicy
	}
	return ScheduleCatchUpPolicy_SCHEDULE_CATCH_UP_POLICY_INVALID
}

func (m *SchedulePolicies) GetCatchUpWindow() *types.Duration {
	if m != nil {
		return m.CatchUpWindow
	}
	return nil
}

func (m *SchedulePolicies) GetPauseOnFailure() bool {
	if m != nil {
		return m.PauseOnFailure
	}
	return false
}

// ScheduleState represents the current runtime state of a schedule.
type ScheduleState struct {
	// Whether the schedule is currently paused.
	Paused bool `protobuf:"varint,1,opt,name=paused,proto3" json:"paused,omitempty"`
	// User-provided reason for pausing.
	PauseReason string `protobuf:"bytes,2,opt,name=pause_reason,json=pauseReason,proto3" json:"pause_reason,omitempty"`
	// Time when the schedule was paused.
	PausedAt             *types.Timestamp `protobuf:"bytes,3,opt,name=paused_at,json=pausedAt,proto3" json:"paused_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ScheduleState) Reset()         { *m = ScheduleState{} }
func (m *ScheduleState) String() string { return proto.CompactTextString(m) }
func (*ScheduleState) ProtoMessage()    {}
func (*ScheduleState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe71309dc9555dc, []int{3}
}
func (m *ScheduleState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduleState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduleState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduleState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleState.Merge(m, src)
}
func (m *ScheduleState) XXX_Size() int {
	return m.Size()
}
func (m *ScheduleState) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleState.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleState proto.InternalMessageInfo

func (m *ScheduleState) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func (m *ScheduleState) GetPauseReason() string {
	if m != nil {
		return m.PauseReason
	}
	return ""
}

func (m *ScheduleState) GetPausedAt() *types.Timestamp {
	if m != nil {
		return m.PausedAt
	}
	return nil
}

// ScheduleActionResult records the result of a single triggered workflow.
type ScheduleActionResult struct {
	// The intended trigger time.
	ScheduledTime *types.Timestamp `protobuf:"bytes,1,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	// The time the workflow was actually started.
	ActualTime *types.Timestamp `protobuf:"bytes,2,opt,name=actual_time,json=actualTime,proto3" json:"actual_time,omitempty"`
	// The target workflow ID that was started.
	WorkflowId string `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	// The run ID of the started workflow.
	RunId string `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// True if this was a backfill run.
	IsBackfill           bool     `protobuf:"varint,5,opt,name=is_backfill,json=isBackfill,proto3" json:"is_backfill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduleActionResult) Reset()         { *m = ScheduleActionResult{} }
func (m *ScheduleActionResult) String() string { return proto.CompactTextString(m) }
func (*ScheduleActionResult) ProtoMessage()    {}
func (*ScheduleActionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe71309dc9555dc, []int{4}
}
func (m *ScheduleActionResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduleActionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduleActionResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduleActionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleActionResult.Merge(m, src)
}
func (m *ScheduleActionResult) XXX_Size() int {
	return m.Size()
}
func (m *ScheduleActionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleActionResult.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleActionResult proto.InternalMessageInfo

func (m *ScheduleActionResult) GetScheduledTime() *types.Timestamp {
	if m != nil {
		return m.ScheduledTime
	}
	return nil
}

func (m *ScheduleActionResult) GetActualTime() *types.Timestamp {
	if m != nil {
		return m.ActualTime
	}
	return nil
}

func (m *ScheduleActionResult) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

func (m *ScheduleActionResult) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

func (m *ScheduleActionResult) GetIsBackfill() bool {
	if m != nil {
		return m.IsBackfill
	}
	return false
}

// ScheduleInfo provides runtime information about the schedule.
type ScheduleInfo struct {
	// When the last run was triggered.
	LastRunTime *types.Timestamp `protobuf:"bytes,1,opt,name=last_run_time,json=lastRunTime,proto3" json:"last_run_time,omitempty"`
	// When the next run will be triggered.
	NextRunTime *types.Timestamp `protobuf:"bytes,2,opt,name=next_run_time,json=nextRunTime,proto3" json:"next_run_time,omitempty"`
	// Total number of triggered runs.
	TotalRuns int64 `protobuf:"varint,3,opt,name=total_runs,json=totalRuns,proto3" json:"total_runs,omitempty"`
	// Number of runs missed (during pause or downtime).
	MissedRuns int64 `protobuf:"varint,4,opt,name=missed_runs,json=missedRuns,proto3" json:"missed_runs,omitempty"`
	// List of recent triggered runs (limited to last 20).
	RecentActions []*ScheduleActionResult `protobuf:"bytes,5,rep,name=recent_actions,json=recentActions,proto3" json:"recent_actions,omitempty"`
	// List of currently running workflow IDs.
	RunningWorkflows []string `protobuf:"bytes,6,rep,name=running_workflows,json=runningWorkflows,proto3" json:"running_workflows,omitempty"`
	// When the schedule was created.
	CreateTime           *types.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ScheduleInfo) Reset()         { *m = ScheduleInfo{} }
func (m *ScheduleInfo) String() string { return proto.CompactTextString(m) }
func (*ScheduleInfo) ProtoMessage()    {}
func (*ScheduleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe71309dc9555dc, []int{5}
}
func (m *ScheduleInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduleInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleInfo.Merge(m, src)
}
func (m *ScheduleInfo) XXX_Size() int {
	return m.Size()
}
func (m *ScheduleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleInfo proto.InternalMessageInfo

func (m *ScheduleInfo) GetLastRunTime() *types.Timestamp {
	if m != nil {
		return m.LastRunTime
	}
	return nil
}

func (m *ScheduleInfo) GetNextRunTime() *types.Timestamp {
	if m != nil {
		return m.NextRunTime
	}
	return nil
}

func (m *ScheduleInfo) GetTotalRuns() int64 {
	if m != nil {
		return m.TotalRuns
	}
	return 0
}

func (m *ScheduleInfo) GetMissedRuns() int64 {
	if m != nil {
		return m.MissedRuns
	}
	return 0
}

func (m *ScheduleInfo) GetRecentActions() []*ScheduleActionResult {
	if m != nil {
		return m.RecentActions
	}
	return nil
}

func (m *ScheduleInfo) GetRunningWorkflows() []string {
	if m != nil {
		return m.RunningWorkflows
	}
	return nil
}

func (m *ScheduleInfo) GetCreateTime() *types.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

// ScheduleListEntry represents a single schedule in a list response.
type ScheduleListEntry struct {
	ScheduleId           string         `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Spec                 *ScheduleSpec  `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	State                *ScheduleState `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Info                 *ScheduleInfo  `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ScheduleListEntry) Reset()         { *m = ScheduleListEntry{} }
func (m *ScheduleListEntry) String() string { return proto.CompactTextString(m) }
func (*ScheduleListEntry) ProtoMessage()    {}
func (*ScheduleListEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fe71309dc9555dc, []int{6}
}
func (m *ScheduleListEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduleListEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduleListEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduleListEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleListEntry.Merge(m, src)
}
func (m *ScheduleListEntry) XXX_Size() int {
	return m.Size()
}
func (m *ScheduleListEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleListEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleListEntry proto.InternalMessageInfo

func (m *ScheduleListEntry) GetScheduleId() string {
	if m != nil {
		return m.ScheduleId
	}
	return ""
}

func (m *ScheduleListEntry) GetSpec() *ScheduleSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ScheduleListEntry) GetState() *ScheduleState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ScheduleListEntry) GetInfo() *ScheduleInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterEnum("uber.cadence.api.v1.ScheduleOverlapPolicy", ScheduleOverlapPolicy_name, ScheduleOverlapPolicy_value)
	proto.RegisterEnum("uber.cadence.api.v1.ScheduleCatchUpPolicy", ScheduleCatchUpPolicy_name, ScheduleCatchUpPolicy_value)
	proto.RegisterType((*ScheduleSpec)(nil), "uber.cadence.api.v1.ScheduleSpec")
	proto.RegisterType((*ScheduleAction)(nil), "uber.cadence.api.v1.ScheduleAction")
	proto.RegisterType((*SchedulePolicies)(nil), "uber.cadence.api.v1.SchedulePolicies")
	proto.RegisterType((*ScheduleState)(nil), "uber.cadence.api.v1.ScheduleState")
	proto.RegisterType((*ScheduleActionResult)(nil), "uber.cadence.api.v1.ScheduleActionResult")
	proto.RegisterType((*ScheduleInfo)(nil), "uber.cadence.api.v1.ScheduleInfo")
	proto.RegisterType((*ScheduleListEntry)(nil), "uber.cadence.api.v1.ScheduleListEntry")
}

func init() {
	proto.RegisterFile("uber/cadence/api/v1/schedule.proto", fileDescriptor_7fe71309dc9555dc)
}

var fileDescriptor_7fe71309dc9555dc = []byte{
	// 1156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x66, 0xe3, 0x9f, 0xda, 0xc7, 0xb1, 0xeb, 0x0e, 0x94, 0x9a, 0xfe, 0xa4, 0x8e, 0xdb, 0xd2,
	0xd0, 0x52, 0x5b, 0x09, 0xaa, 0x00, 0x55, 0xaa, 0xb4, 0x71, 0x1c, 0xc5, 0xc2, 0x8d, 0xcd, 0xd8,
	0x69, 0x04, 0x37, 0xab, 0xf1, 0xee, 0x38, 0x19, 0x65, 0xbd, 0xb3, 0xda, 0x99, 0x4d, 0xe2, 0x6b,
	0xee, 0x78, 0x0e, 0x84, 0x84, 0xc4, 0x03, 0xf0, 0x08, 0x5c, 0xf2, 0x00, 0x5c, 0xa0, 0xbc, 0x00,
	0xaf, 0x80, 0x66, 0x76, 0xd7, 0x71, 0x83, 0xed, 0xe4, 0x72, 0xbe, 0xf9, 0xbe, 0x6f, 0xce, 0x39,
	0x33, 0xe7, 0xec, 0x42, 0x2d, 0x1c, 0xd2, 0xa0, 0x61, 0x13, 0x87, 0x7a, 0x36, 0x6d, 0x10, 0x9f,
	0x35, 0x4e, 0x37, 0x1b, 0xc2, 0x3e, 0xa6, 0x4e, 0xe8, 0xd2, 0xba, 0x1f, 0x70, 0xc9, 0xd1, 0xc7,
	0x8a, 0x53, 0x8f, 0x39, 0x75, 0xe2, 0xb3, 0xfa, 0xe9, 0xe6, 0xfd, 0xb5, 0x23, 0xce, 0x8f, 0x5c,
	0xda, 0xd0, 0x94, 0x61, 0x38, 0x6a, 0x38, 0x61, 0x40, 0x24, 0xe3, 0x5e, 0x24, 0xba, 0xff, 0xf8,
	0xea, 0xbe, 0x64, 0x63, 0x2a, 0x24, 0x19, 0xfb, 0x31, 0xa1, 0x3a, 0xef, 0x64, 0x9b, 0x8f, 0xc7,
	0x89, 0x45, 0xed, 0x37, 0x03, 0x56, 0xfb, 0x71, 0x28, 0x7d, 0x9f, 0xda, 0xe8, 0x39, 0xdc, 0xb6,
	0x03, 0xee, 0x59, 0xf4, 0xdc, 0x0f, 0xa8, 0x10, 0x8c, 0x7b, 0x15, 0xa3, 0x6a, 0x6c, 0xe4, 0x71,
	0x49, 0xc1, 0xad, 0x29, 0x8a, 0xbe, 0x05, 0x10, 0x92, 0x04, 0xd2, 0x52, 0x87, 0x56, 0x56, 0xaa,
	0xc6, 0x46, 0x61, 0xeb, 0x7e, 0x3d, 0x8a, 0xa8, 0x9e, 0x44, 0x54, 0x1f, 0x24, 0x11, 0xe1, 0xbc,
	0x66, 0xab, 0x35, 0x7a, 0x0d, 0x39, 0xea, 0x39, 0x91, 0x30, 0x75, 0xad, 0xf0, 0x16, 0xf5, 0x1c,
	0xb5, 0xaa, 0xfd, 0x91, 0x86, 0x52, 0x12, 0xab, 0x69, 0xab, 0x3a, 0xa0, 0x27, 0x50, 0x3c, 0xe3,
	0xc1, 0xc9, 0xc8, 0xe5, 0x67, 0x96, 0x9c, 0xf8, 0x34, 0x8e, 0x75, 0x35, 0x01, 0x07, 0x13, 0x9f,
	0xa2, 0x07, 0x90, 0x97, 0x44, 0x9c, 0x58, 0x2e, 0x13, 0x52, 0x07, 0x9a, 0xc7, 0x39, 0x05, 0x74,
	0x98, 0x90, 0x68, 0x0b, 0x32, 0xcc, 0xf3, 0x43, 0x19, 0x07, 0xf2, 0xb0, 0x3e, 0xe7, 0x22, 0xea,
	0x3d, 0x32, 0x71, 0x39, 0x71, 0x70, 0x44, 0x45, 0x5f, 0x02, 0x9a, 0x9e, 0xca, 0x1c, 0xcb, 0x0f,
	0xe8, 0x88, 0x9d, 0x57, 0xd2, 0xda, 0xb9, 0x9c, 0xec, 0xb4, 0x9d, 0x9e, 0xc6, 0x11, 0x81, 0x2a,
	0x3d, 0xa7, 0x76, 0xa8, 0x02, 0xb6, 0xe2, 0x92, 0x71, 0xcb, 0x76, 0xb9, 0xa0, 0xba, 0x04, 0x3c,
	0x94, 0x95, 0x8c, 0x3e, 0xfc, 0xb3, 0xff, 0x55, 0x61, 0x27, 0xbe, 0x70, 0xfc, 0x70, 0x6a, 0xd1,
	0xd7, 0x65, 0xe4, 0x4d, 0xa5, 0x1f, 0x44, 0x72, 0x74, 0x08, 0x0f, 0x74, 0x86, 0x0b, 0xdc, 0xb3,
	0xd7, 0xb9, 0xdf, 0x53, 0xea, 0x79, 0xc6, 0x4d, 0x58, 0x0d, 0xa8, 0x0c, 0x26, 0x96, 0xcf, 0x5d,
	0x66, 0x4f, 0x2a, 0xb7, 0xb4, 0x53, 0x75, 0x6e, 0x91, 0xb0, 0x22, 0xf6, 0x34, 0x0f, 0x17, 0x82,
	0xcb, 0x05, 0x7a, 0x05, 0xe9, 0x31, 0x1d, 0xf3, 0x4a, 0x2e, 0x0e, 0x63, 0x9e, 0xf8, 0x1d, 0x1d,
	0x73, 0xac, 0x69, 0x08, 0xc3, 0x1d, 0x41, 0x49, 0x60, 0x1f, 0x5b, 0x44, 0xca, 0x80, 0x0d, 0x43,
	0x49, 0x45, 0x25, 0xaf, 0xb5, 0xcf, 0xe6, 0x6a, 0xfb, 0x9a, 0x6d, 0x4e, 0xc9, 0xb8, 0x2c, 0xae,
	0x20, 0xb5, 0x5f, 0x57, 0xa0, 0x9c, 0x3c, 0x1d, 0x1d, 0x15, 0xa3, 0x02, 0x7d, 0x0f, 0x25, 0x7e,
	0x4a, 0x03, 0x97, 0xf8, 0x49, 0x7a, 0xea, 0xf5, 0x94, 0xb6, 0x5e, 0xcc, 0x3f, 0x25, 0x96, 0x77,
	0x23, 0x49, 0x9c, 0x68, 0x91, 0xcf, 0x2e, 0x11, 0x86, 0xdb, 0x36, 0x91, 0xf6, 0xb1, 0x15, 0x4e,
	0x3d, 0x57, 0x6e, 0xe0, 0xd9, 0x54, 0x9a, 0x83, 0xa9, 0xa7, 0x3d, 0xbb, 0x44, 0xe6, 0x8c, 0xe7,
	0x19, 0xf3, 0x1c, 0x7e, 0x16, 0xbf, 0xd5, 0x25, 0x17, 0x9a, 0x58, 0x1c, 0x6a, 0x3e, 0xda, 0x80,
	0xb2, 0x4f, 0x42, 0x41, 0x2d, 0xee, 0x59, 0x23, 0xc2, 0xdc, 0x30, 0xa0, 0xfa, 0xb9, 0xe6, 0x70,
	0x49, 0xe3, 0x5d, 0x6f, 0x37, 0x42, 0x6b, 0x3f, 0x19, 0x50, 0x9c, 0xce, 0x03, 0x49, 0x24, 0x45,
	0x9f, 0x42, 0x56, 0x73, 0x1c, 0x5d, 0x9d, 0x1c, 0x8e, 0x57, 0x68, 0x1d, 0x56, 0x23, 0xcf, 0x80,
	0x12, 0xc1, 0xbd, 0xb8, 0xb1, 0x0a, 0x1a, 0xc3, 0x1a, 0x42, 0x5f, 0x43, 0x3e, 0x22, 0x5b, 0x44,
	0xde, 0xa0, 0xd1, 0x73, 0x11, 0xd9, 0x94, 0xb5, 0x7f, 0x0d, 0xf8, 0xe4, 0xc3, 0x4e, 0xc7, 0x54,
	0x84, 0xae, 0x44, 0x26, 0x94, 0x92, 0xc1, 0x19, 0xcf, 0x0f, 0xe3, 0x5a, 0xdb, 0xe2, 0x54, 0xa1,
	0x87, 0xcf, 0x1b, 0x28, 0x10, 0x5b, 0x86, 0xc4, 0xbd, 0xe9, 0xe0, 0x82, 0x88, 0xae, 0xc5, 0x8f,
	0xa1, 0x30, 0xd3, 0xf9, 0x3a, 0xa7, 0x3c, 0x86, 0xcb, 0x96, 0x47, 0x77, 0x21, 0x1b, 0x84, 0x9e,
	0xda, 0x8b, 0xc6, 0x41, 0x26, 0x08, 0xbd, 0xb6, 0xa3, 0x74, 0x4c, 0x58, 0x43, 0x62, 0x9f, 0x8c,
	0x98, 0xeb, 0xea, 0x76, 0xcf, 0x61, 0x60, 0x62, 0x3b, 0x46, 0x6a, 0x3f, 0xa7, 0x2e, 0xe7, 0x70,
	0xdb, 0x1b, 0x71, 0xf4, 0x16, 0x8a, 0x2e, 0x11, 0xd2, 0x52, 0x6e, 0x37, 0x4c, 0xb4, 0xa0, 0x04,
	0x38, 0xf4, 0x74, 0xa4, 0x6f, 0xa1, 0xe8, 0xd1, 0xf3, 0x19, 0xfd, 0xf5, 0x89, 0x16, 0x94, 0x20,
	0xd1, 0x3f, 0x02, 0x90, 0x5c, 0x12, 0x57, 0x19, 0x08, 0x9d, 0x68, 0x0a, 0xe7, 0x35, 0x82, 0x43,
	0x4f, 0xa8, 0x84, 0xc6, 0x4c, 0xa8, 0xab, 0xd5, 0xfb, 0x69, 0xbd, 0x0f, 0x11, 0xa4, 0x09, 0x3d,
	0x28, 0x05, 0xd4, 0xa6, 0x9e, 0xb4, 0x88, 0xbe, 0x40, 0x51, 0xc9, 0x54, 0x53, 0x1b, 0x85, 0xad,
	0x2f, 0x96, 0x36, 0xc2, 0xec, 0x65, 0xe3, 0x62, 0x64, 0x10, 0x61, 0x02, 0xbd, 0x84, 0x3b, 0x41,
	0xe8, 0x79, 0xcc, 0x3b, 0xb2, 0x92, 0x82, 0x8b, 0x4a, 0xb6, 0x9a, 0x52, 0x43, 0x37, 0xde, 0x38,
	0x4c, 0x70, 0x75, 0xcb, 0x76, 0x40, 0x89, 0x8c, 0x86, 0x60, 0x3c, 0xb7, 0x96, 0xde, 0x72, 0x44,
	0xd7, 0x1f, 0x9a, 0xbf, 0x0d, 0xb8, 0x93, 0x44, 0xa4, 0x3e, 0x12, 0x2d, 0x4f, 0x06, 0x13, 0x95,
	0x72, 0xf2, 0x92, 0xd4, 0xfd, 0x46, 0x5f, 0x1a, 0x48, 0xa0, 0xb6, 0x83, 0x5e, 0x43, 0x5a, 0xf8,
	0xd4, 0x8e, 0x2b, 0xbd, 0xbe, 0x34, 0x51, 0xf5, 0xad, 0xc5, 0x9a, 0x8e, 0xbe, 0x81, 0x8c, 0x50,
	0x9d, 0x16, 0x77, 0x48, 0x6d, 0xb9, 0x4e, 0x31, 0x71, 0x24, 0x50, 0x07, 0x32, 0x6f, 0xc4, 0x75,
	0xf5, 0xaf, 0x3b, 0x50, 0x3d, 0x2a, 0xac, 0xe9, 0x2f, 0x7e, 0x5f, 0x81, 0xbb, 0x73, 0xa7, 0x19,
	0x7a, 0x02, 0x8f, 0xfb, 0xcd, 0xbd, 0xd6, 0xce, 0x41, 0xa7, 0x65, 0x75, 0xdf, 0xb7, 0x70, 0xc7,
	0xec, 0x59, 0xbd, 0x6e, 0xa7, 0xdd, 0xfc, 0xc1, 0x6a, 0xef, 0xbf, 0x37, 0x3b, 0xed, 0x9d, 0xf2,
	0x47, 0xa8, 0x0a, 0x0f, 0x17, 0x91, 0xfa, 0xdf, 0xb5, 0x7b, 0x65, 0x03, 0x7d, 0x0e, 0xb5, 0x45,
	0x8c, 0xed, 0x83, 0xdd, 0xdd, 0x16, 0xb6, 0xba, 0xfb, 0xad, 0xf2, 0xca, 0x0d, 0x78, 0x66, 0xa7,
	0x53, 0x4e, 0xa1, 0x0d, 0x78, 0xba, 0x88, 0xd7, 0x34, 0xf7, 0x9b, 0xad, 0x8e, 0xd5, 0x1d, 0xec,
	0xb5, 0x70, 0x39, 0x8d, 0x5e, 0xc2, 0xf3, 0x45, 0xcc, 0x41, 0x0b, 0xbf, 0x6b, 0xef, 0x9b, 0x83,
	0x56, 0x4c, 0xce, 0xa0, 0x67, 0xb0, 0xbe, 0x88, 0x6c, 0x76, 0x3a, 0xdd, 0x43, 0x7d, 0x7a, 0xf6,
	0xc5, 0x2f, 0xc6, 0x65, 0xb9, 0x3e, 0x18, 0xd4, 0xe8, 0x29, 0x54, 0xa7, 0x06, 0x4d, 0x73, 0xd0,
	0xdc, 0xb3, 0x0e, 0xe6, 0xd4, 0x6b, 0x1d, 0x1e, 0x2d, 0x64, 0xc5, 0x05, 0x9b, 0x2d, 0xe9, 0x55,
	0x4a, 0x54, 0xaa, 0x65, 0x0c, 0x5d, 0xa4, 0x6d, 0xf6, 0xe7, 0xc5, 0x9a, 0xf1, 0xd7, 0xc5, 0x9a,
	0xf1, 0xcf, 0xc5, 0x9a, 0x01, 0xf7, 0x6c, 0x3e, 0x9e, 0xf7, 0x1e, 0xb6, 0xa7, 0xd3, 0xbd, 0xa7,
	0x7a, 0xa0, 0x67, 0xfc, 0xb8, 0x79, 0xc4, 0xe4, 0x71, 0x38, 0xac, 0xdb, 0x7c, 0xdc, 0x98, 0xfd,
	0x5d, 0x7c, 0xc5, 0x1c, 0xb7, 0x71, 0xc4, 0xa3, 0x9f, 0xcb, 0xf8, 0xdf, 0xf1, 0x0d, 0xf1, 0xd9,
	0xe9, 0xe6, 0x30, 0xab, 0xb1, 0xaf, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x09, 0x4b, 0x51, 0x03,
	0xd9, 0x0a, 0x00, 0x00,
}

func (m *ScheduleSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduleSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduleSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.EndTime != nil {
		{
			size, err := m.EndTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.StartTime != nil {
		{
			size, err := m.StartTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CronExpression) > 0 {
		i -= len(m.CronExpression)
		copy(dAtA[i:], m.CronExpression)
		i = encodeVarintSchedule(dAtA, i, uint64(len(m.CronExpression)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ScheduleAction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduleAction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduleAction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.SearchAttributes != nil {
		{
			size, err := m.SearchAttributes.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.Memo != nil {
		{
			size, err := m.Memo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.RetryPolicy != nil {
		{
			size, err := m.RetryPolicy.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.TaskStartToCloseTimeout != nil {
		{
			size, err := m.TaskStartToCloseTimeout.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.ExecutionStartToCloseTimeout != nil {
		{
			size, err := m.ExecutionStartToCloseTimeout.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.WorkflowIdPrefix) > 0 {
		i -= len(m.WorkflowIdPrefix)
		copy(dAtA[i:], m.WorkflowIdPrefix)
		i = encodeVarintSchedule(dAtA, i, uint64(len(m.WorkflowIdPrefix)))
		i--
		dAtA[i] = 0x22
	}
	if m.Input != nil {
		{
			size, err := m.Input.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TaskList) > 0 {
		i -= len(m.TaskList)
		copy(dAtA[i:], m.TaskList)
		i = encodeVarintSchedule(dAtA, i, uint64(len(m.TaskList)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.WorkflowType) > 0 {
		i -= len(m.WorkflowType)
		copy(dAtA[i:], m.WorkflowType)
		i = encodeVarintSchedule(dAtA, i, uint64(len(m.WorkflowType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SchedulePolicies) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SchedulePolicies) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SchedulePolicies) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.PauseOnFailure {
		i--
		if m.PauseOnFailure {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.CatchUpWindow != nil {
		{
			size, err := m.CatchUpWindow.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.CatchUpPolicy != 0 {
		i = encodeVarintSchedule(dAtA, i, uint64(m.CatchUpPolicy))
		i--
		dAtA[i] = 0x10
	}
	if m.OverlapPolicy != 0 {
		i = encodeVarintSchedule(dAtA, i, uint64(m.OverlapPolicy))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ScheduleState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduleState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduleState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.PausedAt != nil {
		{
			size, err := m.PausedAt.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PauseReason) > 0 {
		i -= len(m.PauseReason)
		copy(dAtA[i:], m.PauseReason)
		i = encodeVarintSchedule(dAtA, i, uint64(len(m.PauseReason)))
		i--
		dAtA[i] = 0x12
	}
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ScheduleActionResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduleActionResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduleActionResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.IsBackfill {
		i--
		if m.IsBackfill {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.RunId) > 0 {
		i -= len(m.RunId)
		copy(dAtA[i:], m.RunId)
		i = encodeVarintSchedule(dAtA, i, uint64(len(m.RunId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.WorkflowId) > 0 {
		i -= len(m.WorkflowId)
		copy(dAtA[i:], m.WorkflowId)
		i = encodeVarintSchedule(dAtA, i, uint64(len(m.WorkflowId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ActualTime != nil {
		{
			size, err := m.ActualTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.ScheduledTime != nil {
		{
			size, err := m.ScheduledTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ScheduleInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduleInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduleInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.CreateTime != nil {
		{
			size, err := m.CreateTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if len(m.RunningWorkflows) > 0 {
		for iNdEx := len(m.RunningWorkflows) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RunningWorkflows[iNdEx])
			copy(dAtA[i:], m.RunningWorkflows[iNdEx])
			i = encodeVarintSchedule(dAtA, i, uint64(len(m.RunningWorkflows[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.RecentActions) > 0 {
		for iNdEx := len(m.RecentActions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RecentActions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSchedule(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.MissedRuns != 0 {
		i = encodeVarintSchedule(dAtA, i, uint64(m.MissedRuns))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalRuns != 0 {
		i = encodeVarintSchedule(dAtA, i, uint64(m.TotalRuns))
		i--
		dAtA[i] = 0x18
	}
	if m.NextRunTime != nil {
		{
			size, err := m.NextRunTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.LastRunTime != nil {
		{
			size, err := m.LastRunTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ScheduleListEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduleListEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduleListEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Info != nil {
		{
			size, err := m.Info.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.State != nil {
		{
			size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Spec != nil {
		{
			size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ScheduleId) > 0 {
		i -= len(m.ScheduleId)
		copy(dAtA[i:], m.ScheduleId)
		i = encodeVarintSchedule(dAtA, i, uint64(len(m.ScheduleId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSchedule(dAtA []byte, offset int, v uint64) int {
	offset -= sovSchedule(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ScheduleSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CronExpression)
	if l > 0 {
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.StartTime != nil {
		l = m.StartTime.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.EndTime != nil {
		l = m.EndTime.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ScheduleAction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WorkflowType)
	if l > 0 {
		n += 1 + l + sovSchedule(uint64(l))
	}
	l = len(m.TaskList)
	if l > 0 {
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.Input != nil {
		l = m.Input.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	l = len(m.WorkflowIdPrefix)
	if l > 0 {
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.ExecutionStartToCloseTimeout != nil {
		l = m.ExecutionStartToCloseTimeout.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.TaskStartToCloseTimeout != nil {
		l = m.TaskStartToCloseTimeout.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.RetryPolicy != nil {
		l = m.RetryPolicy.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.Memo != nil {
		l = m.Memo.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.SearchAttributes != nil {
		l = m.SearchAttributes.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SchedulePolicies) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OverlapPolicy != 0 {
		n += 1 + sovSchedule(uint64(m.OverlapPolicy))
	}
	if m.CatchUpPolicy != 0 {
		n += 1 + sovSchedule(uint64(m.CatchUpPolicy))
	}
	if m.CatchUpWindow != nil {
		l = m.CatchUpWindow.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.PauseOnFailure {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ScheduleState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Paused {
		n += 2
	}
	l = len(m.PauseReason)
	if l > 0 {
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.PausedAt != nil {
		l = m.PausedAt.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ScheduleActionResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ScheduledTime != nil {
		l = m.ScheduledTime.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.ActualTime != nil {
		l = m.ActualTime.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	l = len(m.WorkflowId)
	if l > 0 {
		n += 1 + l + sovSchedule(uint64(l))
	}
	l = len(m.RunId)
	if l > 0 {
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.IsBackfill {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ScheduleInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LastRunTime != nil {
		l = m.LastRunTime.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.NextRunTime != nil {
		l = m.NextRunTime.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.TotalRuns != 0 {
		n += 1 + sovSchedule(uint64(m.TotalRuns))
	}
	if m.MissedRuns != 0 {
		n += 1 + sovSchedule(uint64(m.MissedRuns))
	}
	if len(m.RecentActions) > 0 {
		for _, e := range m.RecentActions {
			l = e.Size()
			n += 1 + l + sovSchedule(uint64(l))
		}
	}
	if len(m.RunningWorkflows) > 0 {
		for _, s := range m.RunningWorkflows {
			l = len(s)
			n += 1 + l + sovSchedule(uint64(l))
		}
	}
	if m.CreateTime != nil {
		l = m.CreateTime.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ScheduleListEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ScheduleId)
	if l > 0 {
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.Spec != nil {
		l = m.Spec.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.State != nil {
		l = m.State.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.Info != nil {
		l = m.Info.Size()
		n += 1 + l + sovSchedule(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSchedule(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSchedule(x uint64) (n int) {
	return sovSchedule(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ScheduleSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduleSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduleSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CronExpression", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CronExpression = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StartTime == nil {
				m.StartTime = &types.Timestamp{}
			}
			if err := m.StartTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EndTime == nil {
				m.EndTime = &types.Timestamp{}
			}
			if err := m.EndTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduleAction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduleAction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduleAction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkflowType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkflowType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskList = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Input", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Input == nil {
				m.Input = &Payload{}
			}
			if err := m.Input.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkflowIdPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkflowIdPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutionStartToCloseTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExecutionStartToCloseTimeout == nil {
				m.ExecutionStartToCloseTimeout = &types.Duration{}
			}
			if err := m.ExecutionStartToCloseTimeout.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskStartToCloseTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TaskStartToCloseTimeout == nil {
				m.TaskStartToCloseTimeout = &types.Duration{}
			}
			if err := m.TaskStartToCloseTimeout.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetryPolicy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RetryPolicy == nil {
				m.RetryPolicy = &RetryPolicy{}
			}
			if err := m.RetryPolicy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Memo == nil {
				m.Memo = &Memo{}
			}
			if err := m.Memo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SearchAttributes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SearchAttributes == nil {
				m.SearchAttributes = &SearchAttributes{}
			}
			if err := m.SearchAttributes.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SchedulePolicies) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SchedulePolicies: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SchedulePolicies: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OverlapPolicy", wireType)
			}
			m.OverlapPolicy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OverlapPolicy |= ScheduleOverlapPolicy(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CatchUpPolicy", wireType)
			}
			m.CatchUpPolicy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CatchUpPolicy |= ScheduleCatchUpPolicy(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CatchUpWindow", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CatchUpWindow == nil {
				m.CatchUpWindow = &types.Duration{}
			}
			if err := m.CatchUpWindow.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PauseOnFailure", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PauseOnFailure = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduleState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduleState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduleState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PauseReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PauseReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PausedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PausedAt == nil {
				m.PausedAt = &types.Timestamp{}
			}
			if err := m.PausedAt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduleActionResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduleActionResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduleActionResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduledTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ScheduledTime == nil {
				m.ScheduledTime = &types.Timestamp{}
			}
			if err := m.ScheduledTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ActualTime == nil {
				m.ActualTime = &types.Timestamp{}
			}
			if err := m.ActualTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkflowId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkflowId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RunId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RunId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsBackfill", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsBackfill = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduleInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduleInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduleInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastRunTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastRunTime == nil {
				m.LastRunTime = &types.Timestamp{}
			}
			if err := m.LastRunTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextRunTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NextRunTime == nil {
				m.NextRunTime = &types.Timestamp{}
			}
			if err := m.NextRunTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRuns", wireType)
			}
			m.TotalRuns = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalRuns |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MissedRuns", wireType)
			}
			m.MissedRuns = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MissedRuns |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecentActions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecentActions = append(m.RecentActions, &ScheduleActionResult{})
			if err := m.RecentActions[len(m.RecentActions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RunningWorkflows", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RunningWorkflows = append(m.RunningWorkflows, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreateTime == nil {
				m.CreateTime = &types.Timestamp{}
			}
			if err := m.CreateTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduleListEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduleListEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduleListEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduleId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScheduleId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Spec == nil {
				m.Spec = &ScheduleSpec{}
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.State == nil {
				m.State = &ScheduleState{}
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Info == nil {
				m.Info = &ScheduleInfo{}
			}
			if err := m.Info.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSchedule(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSchedule
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSchedule
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSchedule
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSchedule
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSchedule
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSchedule        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSchedule          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSchedule = fmt.Errorf("proto: unexpected end of group")
)
