// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uber/cadence/api/v1/service_semaphore.proto

package apiv1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CreateSemaphoreRequest struct {
	Domain        string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	SemaphoreName string `protobuf:"bytes,2,opt,name=semaphore_name,json=semaphoreName,proto3" json:"semaphore_name,omitempty"`
	// Total number of tokens. Must be positive.
	Size_ int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Optional. Number of tokens in each bucket, the server picks a default if unset, and rejects values
	// above its maximum.
	BucketSize int32 `protobuf:"varint,4,opt,name=bucket_size,json=bucketSize,proto3" json:"bucket_size,omitempty"`
	// Optional. How long an acquire waits for a token when it does not set its own timeout.
	// Unset or zero means the server's default applies.
	DefaultWaitTimeout   *types.Duration `protobuf:"bytes,5,opt,name=default_wait_timeout,json=defaultWaitTimeout,proto3" json:"default_wait_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateSemaphoreRequest) Reset()         { *m = CreateSemaphoreRequest{} }
func (m *CreateSemaphoreRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSemaphoreRequest) ProtoMessage()    {}
func (*CreateSemaphoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60f52eba354a86a4, []int{0}
}
func (m *CreateSemaphoreRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateSemaphoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateSemaphoreRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateSemaphoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSemaphoreRequest.Merge(m, src)
}
func (m *CreateSemaphoreRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateSemaphoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSemaphoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSemaphoreRequest proto.InternalMessageInfo

func (m *CreateSemaphoreRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *CreateSemaphoreRequest) GetSemaphoreName() string {
	if m != nil {
		return m.SemaphoreName
	}
	return ""
}

func (m *CreateSemaphoreRequest) GetSize_() int32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *CreateSemaphoreRequest) GetBucketSize() int32 {
	if m != nil {
		return m.BucketSize
	}
	return 0
}

func (m *CreateSemaphoreRequest) GetDefaultWaitTimeout() *types.Duration {
	if m != nil {
		return m.DefaultWaitTimeout
	}
	return nil
}

type CreateSemaphoreResponse struct {
	// The semaphore as stored, with defaults filled in.
	Semaphore            *Semaphore `protobuf:"bytes,1,opt,name=semaphore,proto3" json:"semaphore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateSemaphoreResponse) Reset()         { *m = CreateSemaphoreResponse{} }
func (m *CreateSemaphoreResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSemaphoreResponse) ProtoMessage()    {}
func (*CreateSemaphoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60f52eba354a86a4, []int{1}
}
func (m *CreateSemaphoreResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateSemaphoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateSemaphoreResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateSemaphoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSemaphoreResponse.Merge(m, src)
}
func (m *CreateSemaphoreResponse) XXX_Size() int {
	return m.Size()
}
func (m *CreateSemaphoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSemaphoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSemaphoreResponse proto.InternalMessageInfo

func (m *CreateSemaphoreResponse) GetSemaphore() *Semaphore {
	if m != nil {
		return m.Semaphore
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateSemaphoreRequest)(nil), "uber.cadence.api.v1.CreateSemaphoreRequest")
	proto.RegisterType((*CreateSemaphoreResponse)(nil), "uber.cadence.api.v1.CreateSemaphoreResponse")
}

func init() {
	proto.RegisterFile("uber/cadence/api/v1/service_semaphore.proto", fileDescriptor_60f52eba354a86a4)
}

var fileDescriptor_60f52eba354a86a4 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcb, 0x6a, 0xdb, 0x40,
	0x14, 0x65, 0x5a, 0xdb, 0xe0, 0x71, 0x1f, 0x30, 0x6d, 0x6d, 0xd5, 0x0b, 0xd5, 0xb8, 0x14, 0x0c,
	0x6e, 0x67, 0x90, 0xbb, 0x6c, 0x37, 0x75, 0xbb, 0x29, 0x85, 0x62, 0xe4, 0x80, 0x21, 0x1b, 0x31,
	0x92, 0xae, 0xe5, 0x21, 0x92, 0x46, 0x96, 0x66, 0x14, 0x08, 0xf9, 0xc0, 0x2c, 0xb3, 0xcd, 0x2e,
	0xf8, 0x4b, 0x82, 0x25, 0x59, 0xce, 0x43, 0x8b, 0xec, 0xa4, 0xf3, 0xb8, 0x73, 0xcf, 0xe5, 0xe0,
	0xa9, 0x76, 0x21, 0x65, 0x1e, 0xf7, 0x21, 0xf6, 0x80, 0xf1, 0x44, 0xb0, 0xdc, 0x62, 0x19, 0xa4,
	0xb9, 0xf0, 0xc0, 0xc9, 0x20, 0xe2, 0xc9, 0x46, 0xa6, 0x40, 0x93, 0x54, 0x2a, 0x49, 0xde, 0xed,
	0xc5, 0xb4, 0x12, 0x53, 0x9e, 0x08, 0x9a, 0x5b, 0x43, 0x33, 0x90, 0x32, 0x08, 0x81, 0x15, 0x12,
	0x57, 0xaf, 0x99, 0xaf, 0x53, 0xae, 0x84, 0x8c, 0x4b, 0xd3, 0xf0, 0x73, 0xf3, 0x0b, 0x0f, 0x26,
	0x8f, 0x6f, 0x10, 0xee, 0xff, 0x4e, 0x81, 0x2b, 0x58, 0x1e, 0x18, 0x1b, 0xb6, 0x1a, 0x32, 0x45,
	0xfa, 0xb8, 0xe3, 0xcb, 0x88, 0x8b, 0xd8, 0x40, 0x23, 0x34, 0xe9, 0xda, 0xd5, 0x1f, 0xf9, 0x82,
	0xdf, 0xd4, 0x53, 0x9c, 0x98, 0x47, 0x60, 0xbc, 0x28, 0xf8, 0xd7, 0x35, 0xfa, 0x9f, 0x47, 0x40,
	0x08, 0x6e, 0x65, 0xe2, 0x02, 0x8c, 0x97, 0x23, 0x34, 0x69, 0xdb, 0xc5, 0x37, 0xf9, 0x84, 0x7b,
	0xae, 0xf6, 0xce, 0x40, 0x39, 0x05, 0xd5, 0x2a, 0x28, 0x5c, 0x42, 0xcb, 0xbd, 0xe0, 0x1f, 0x7e,
	0xef, 0xc3, 0x9a, 0xeb, 0x50, 0x39, 0xe7, 0x5c, 0x28, 0x47, 0x89, 0x08, 0xa4, 0x56, 0x46, 0x7b,
	0x84, 0x26, 0xbd, 0xd9, 0x47, 0x5a, 0x46, 0xa6, 0x87, 0xc8, 0xf4, 0x4f, 0x15, 0xd9, 0x26, 0x95,
	0x6d, 0xc5, 0x85, 0x3a, 0x29, 0x4d, 0xe3, 0x15, 0x1e, 0x3c, 0x89, 0x96, 0x25, 0x32, 0xce, 0x80,
	0xfc, 0xc4, 0xdd, 0x7a, 0xdb, 0x22, 0x5e, 0x6f, 0x66, 0xd2, 0x86, 0x23, 0xd3, 0xa3, 0xf5, 0x68,
	0x98, 0x5d, 0xe2, 0x57, 0x35, 0xfe, 0x6b, 0xf1, 0x97, 0x84, 0xf8, 0xed, 0xa3, 0x87, 0xc8, 0xb4,
	0x71, 0x5a, 0xf3, 0xa5, 0x87, 0x5f, 0x9f, 0x27, 0x2e, 0x77, 0x9f, 0x6f, 0xaf, 0x76, 0x26, 0xba,
	0xde, 0x99, 0xe8, 0x76, 0x67, 0x22, 0x3c, 0xf0, 0x64, 0xd4, 0x64, 0x9f, 0x7f, 0xa8, 0x9d, 0xcb,
	0xb2, 0x55, 0x8b, 0xfd, 0xd1, 0x16, 0xe8, 0xd4, 0x0a, 0x84, 0xda, 0x68, 0x97, 0x7a, 0x32, 0x62,
	0xf7, 0x2b, 0xf2, 0x4d, 0xf8, 0x21, 0x0b, 0x64, 0xd9, 0xa7, 0xaa, 0x2f, 0x3f, 0x78, 0x22, 0x72,
	0xcb, 0xed, 0x14, 0xd8, 0xf7, 0xbb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0x31, 0x8c, 0xa2, 0xb5,
	0x02, 0x00, 0x00,
}

func (m *CreateSemaphoreRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateSemaphoreRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateSemaphoreRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.DefaultWaitTimeout != nil {
		{
			size, err := m.DefaultWaitTimeout.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintServiceSemaphore(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.BucketSize != 0 {
		i = encodeVarintServiceSemaphore(dAtA, i, uint64(m.BucketSize))
		i--
		dAtA[i] = 0x20
	}
	if m.Size_ != 0 {
		i = encodeVarintServiceSemaphore(dAtA, i, uint64(m.Size_))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SemaphoreName) > 0 {
		i -= len(m.SemaphoreName)
		copy(dAtA[i:], m.SemaphoreName)
		i = encodeVarintServiceSemaphore(dAtA, i, uint64(len(m.SemaphoreName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintServiceSemaphore(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateSemaphoreResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateSemaphoreResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateSemaphoreResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Semaphore != nil {
		{
			size, err := m.Semaphore.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintServiceSemaphore(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintServiceSemaphore(dAtA []byte, offset int, v uint64) int {
	offset -= sovServiceSemaphore(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CreateSemaphoreRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovServiceSemaphore(uint64(l))
	}
	l = len(m.SemaphoreName)
	if l > 0 {
		n += 1 + l + sovServiceSemaphore(uint64(l))
	}
	if m.Size_ != 0 {
		n += 1 + sovServiceSemaphore(uint64(m.Size_))
	}
	if m.BucketSize != 0 {
		n += 1 + sovServiceSemaphore(uint64(m.BucketSize))
	}
	if m.DefaultWaitTimeout != nil {
		l = m.DefaultWaitTimeout.Size()
		n += 1 + l + sovServiceSemaphore(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CreateSemaphoreResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Semaphore != nil {
		l = m.Semaphore.Size()
		n += 1 + l + sovServiceSemaphore(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovServiceSemaphore(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozServiceSemaphore(x uint64) (n int) {
	return sovServiceSemaphore(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CreateSemaphoreRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServiceSemaphore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateSemaphoreRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateSemaphoreRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SemaphoreName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SemaphoreName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BucketSize", wireType)
			}
			m.BucketSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BucketSize |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultWaitTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DefaultWaitTimeout == nil {
				m.DefaultWaitTimeout = &types.Duration{}
			}
			if err := m.DefaultWaitTimeout.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServiceSemaphore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateSemaphoreResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServiceSemaphore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateSemaphoreResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateSemaphoreResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Semaphore", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Semaphore == nil {
				m.Semaphore = &Semaphore{}
			}
			if err := m.Semaphore.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServiceSemaphore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServiceSemaphore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipServiceSemaphore(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowServiceSemaphore
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServiceSemaphore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthServiceSemaphore
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupServiceSemaphore
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthServiceSemaphore
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthServiceSemaphore        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowServiceSemaphore          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupServiceSemaphore = fmt.Errorf("proto: unexpected end of group")
)
